[package]
name = "plugin_settings"
version = "0.1.0"
edition = "2021"
description = "Demonstrates configuration files and FakeConVars"

[lib]
crate-type = ["rlib"]

[dependencies]
cs2rust-core.workspace = true
tracing.workspace = true
serde.workspace = true
